import { Product } from "~/types"

export const useProductsStore = defineStore("products", {
  state: () => ({
    allProducts: [
      {
        category: "Asian",
        name: "Sushi Roll",
        calories: 250,
        carbs: 35,
        protein: 15,
        fat: 5,
        price: 8.99,
        url: "https://images.pexels.com/photos/5900883/pexels-photo-5900883.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 0,
      },
      {
        category: "Asian",
        name: "Pad Thai",
        calories: 400,
        carbs: 50,
        protein: 10,
        fat: 15,
        price: 9.99,
        url: "/images/asian.png",
        id: 1,
      },
      {
        category: "Asian",
        name: "Miso Soup",
        calories: 70,
        carbs: 10,
        protein: 5,
        fat: 2,
        price: 3.99,
        url: "/images/asian.png",
        id: 2,
      },
      {
        category: "Asian",
        name: "Bibimbap",
        calories: 500,
        carbs: 60,
        protein: 20,
        fat: 12,
        price: 11.99,
        url: "https://images.pexels.com/photos/12973148/pexels-photo-12973148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        id: 3,
      },
      {
        category: "Mexican",
        name: "Taco",
        calories: 200,
        carbs: 20,
        protein: 12,
        fat: 8,
        price: 5.99,
        url: "https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        id: 4,
      },
      {
        category: "Mexican",
        name: "Burrito",
        calories: 450,
        carbs: 40,
        protein: 20,
        fat: 15,
        price: 7.49,
        url: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        id: 5,
      },
      {
        category: "Mexican",
        name: "Enchiladas",
        calories: 300,
        carbs: 25,
        protein: 15,
        fat: 12,
        price: 6.99,
        url: "https://images.pexels.com/photos/9772454/pexels-photo-9772454.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        id: 6,
      },
      {
        category: "Mexican",
        name: "Quesadilla",
        calories: 350,
        carbs: 30,
        protein: 18,
        fat: 15,
        price: 6.49,
        url: "https://images.pexels.com/photos/58722/pexels-photo-58722.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        id: 7,
      },
      {
        category: "Fast Food",
        name: "Cheeseburger",
        calories: 350,
        carbs: 30,
        protein: 20,
        fat: 18,
        price: 6.49,
        url: "https://images.pexels.com/photos/2983103/pexels-photo-2983103.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 8,
      },
      {
        category: "Fast Food",
        name: "French Fries",
        calories: 300,
        carbs: 40,
        protein: 4,
        fat: 15,
        price: 3.99,
        url: "https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 9,
      },
      {
        category: "Fast Food",
        name: "Chicken Nuggets",
        calories: 250,
        carbs: 20,
        protein: 15,
        fat: 12,
        price: 4.99,
        url: "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 10,
      },
      {
        category: "Fast Food",
        name: "Pizza Slice",
        calories: 320,
        carbs: 30,
        protein: 12,
        fat: 16,
        price: 2.99,
        url: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 11,
      },
      {
        category: "American",
        name: "BBQ Ribs",
        calories: 450,
        carbs: 10,
        protein: 30,
        fat: 35,
        price: 12.99,
        url: "https://images.pexels.com/photos/410648/pexels-photo-410648.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 12,
      },
      {
        category: "American",
        name: "Hamburger",
        calories: 400,
        carbs: 25,
        protein: 18,
        fat: 22,
        price: 8.99,
        url: "https://images.pexels.com/photos/2983103/pexels-photo-2983103.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 13,
      },
      {
        category: "American",
        name: "Caesar Salad",
        calories: 150,
        carbs: 10,
        protein: 8,
        fat: 10,
        price: 5.99,
        url: "https://images.pexels.com/photos/16849912/pexels-photo-16849912/free-photo-of-healthy-salad-with-cucumber.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 14,
      },
      {
        category: "American",
        name: "Hot Dog",
        calories: 280,
        carbs: 20,
        protein: 10,
        fat: 18,
        price: 4.99,
        url: "https://images.pexels.com/photos/3023479/pexels-photo-3023479.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 15,
      },
      {
        category: "Vegetarian",
        name: "Caprese Salad",
        calories: 200,
        carbs: 8,
        protein: 10,
        fat: 15,
        price: 6.99,
        url: "https://images.pexels.com/photos/16849912/pexels-photo-16849912/free-photo-of-healthy-salad-with-cucumber.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 16,
      },
      {
        category: "Vegetarian",
        name: "Veggie Burger",
        calories: 300,
        carbs: 25,
        protein: 15,
        fat: 12,
        price: 7.49,
        url: "https://images.pexels.com/photos/16833332/pexels-photo-16833332/free-photo-of-burger-on-plate.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 17,
      },
      {
        category: "Vegetarian",
        name: "Mushroom Risotto",
        calories: 350,
        carbs: 40,
        protein: 10,
        fat: 8,
        price: 9.99,
        url: "https://images.pexels.com/photos/2067418/pexels-photo-2067418.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 18,
      },
      {
        category: "Italian",
        name: "Margherita Pizza",
        calories: 280,
        carbs: 35,
        protein: 12,
        fat: 10,
        price: 10.99,
        url: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 19,
      },
      {
        category: "Italian",
        name: "Pasta Carbonara",
        calories: 400,
        carbs: 50,
        protein: 18,
        fat: 20,
        price: 11.99,
        url: "https://images.pexels.com/photos/2703468/pexels-photo-2703468.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 20,
      },
      {
        category: "Italian",
        name: "Tiramisu",
        calories: 320,
        carbs: 25,
        protein: 5,
        fat: 22,
        price: 7.99,
        url: "https://images.pexels.com/photos/12035685/pexels-photo-12035685.jpeg?auto=compress&cs=tinysrgb&w=800",
        id: 21,
      },
    ] as Product[],
  }),
  getters: {
    getAllUniqueCategories: (state) => {
      let categories = state.allProducts.map((product) => product.category)
      categories = categories.filter(
        (category, index, arr) => arr.indexOf(category) == index
      )
      return categories
    },
    getProductsByCategory: (state) => {
      return (category: string) => {
        return state.allProducts.filter(
          (product) =>
            product.category.toLowerCase().replace(" ", "") == category
        )
      }
    },
    getProduct: (state) => {
      return (id: number) => {
        return state.allProducts.find((product) => product.id == id)
      }
    },
  },
})
